name: rbx_rewards
description: "RBX Rewards - Official Application founded and developed by Abdelkrim Salaghe & Youssef"

# -----------------------------------------------------------------------------
# Authors & Intellectual Property
# -----------------------------------------------------------------------------
# Founder & Lead Architect: Abdelkrim Salaghe
# Co-Founder & Publishing Partner: Youssef
# Copyright (c) 2024-2026 Abdelkrim Salaghe & Youssef. All rights reserved.
# -----------------------------------------------------------------------------

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.4.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  flame: ^1.37.0
  shared_preferences: ^2.5.5
  scratcher: ^2.5.0
  supabase_flutter: ^2.12.4
  connectivity_plus: ^7.1.1
  uuid: ^4.4.0
  flutter_secure_storage: ^10.3.0
  google_mobile_ads: ^5.2.0
  app_tracking_transparency: ^2.0.6
  url_launcher: ^6.3.0
  tapjoy_offerwall: ^14.6.0
  pubscale_offerwall_plugin: ^0.0.4
  flutter_riverpod: ^2.6.1
  hive_flutter: ^1.1.0
  crypto: ^3.0.7
  device_info_plus: ^13.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/json/
    - assets/icons/
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path_ios: "assets/images/app_icon_ios.png"
  image_path_android: "assets/images/app_icon_ios.png"
  image_path: "assets/images/app_icon_ios.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon_android_adaptive_fore.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/app_icon_ios.png"