#!/usr/bin/env dart
// ─────────────────────────────────────────────────────────────────────────────
// RBX Rewards — Secret Generator
//
// Reads env.json → writes lib/core/config/app_secrets.dart
//
// Runs automatically before every flutter run / flutter build via:
//   • Android: Gradle preBuild hook (android/app/build.gradle.kts)
//   • iOS:     Xcode Run Script Build Phase
//
// Developers never need to type --dart-define flags.
// The generated file is git-ignored — keys never touch GitHub.
// ─────────────────────────────────────────────────────────────────────────────

import 'dart:convert';
import 'dart:io';

void main(List<String> args) {
  // Support: dart run tool/generate_secrets.dart --env=env.test.json
  final envArg = args.firstWhere(
    (a) => a.startsWith('--env='),
    orElse: () => '--env=env.json',
  );
  final envFileName = envArg.replaceFirst('--env=', '');

  final projectRoot = _findProjectRoot();
  final envFile = File('${projectRoot.path}/$envFileName');
  final outputFile = File('${projectRoot.path}/lib/core/config/app_secrets.dart');

  if (!envFile.existsSync()) {
    stderr.writeln('');
    stderr.writeln('  ⚠️  $envFileName not found at ${envFile.path}');
    stderr.writeln('  Run: Copy-Item env.example.json $envFileName');
    stderr.writeln('  Then fill in your real API keys.');
    stderr.writeln('');
    // Write empty-defaults file so the app compiles even without env.json
    _writeSecrets(outputFile, <String, String>{});
    exit(0);
  }

  final Map<String, dynamic> raw;
  try {
    raw = jsonDecode(envFile.readAsStringSync()) as Map<String, dynamic>;
  } catch (e) {
    stderr.writeln('❌ Failed to parse $envFileName: $e');
    exit(1);
  }

  final secrets = raw.map((k, v) => MapEntry(k, v.toString()));
  _writeSecrets(outputFile, secrets);
  stdout.writeln('✅ app_secrets.dart generated from $envFileName (${secrets.length} keys)');
}

void _writeSecrets(File outputFile, Map<String, String> secrets) {
  outputFile.parent.createSync(recursive: true);

  final buf = StringBuffer();
  buf.writeln('// GENERATED FILE — DO NOT EDIT MANUALLY');
  buf.writeln('// Auto-generated by tool/generate_secrets.dart');
  buf.writeln('// Source: env.json (git-ignored — never committed)');
  buf.writeln('// Regenerated automatically before every flutter run/build.');
  buf.writeln('');
  buf.writeln('// ignore_for_file: constant_identifier_names, lines_longer_than_80_chars');
  buf.writeln('');
  buf.writeln('abstract final class AppSecrets {');

  // All known keys with empty-string defaults so the app always compiles
  final defaults = <String, String>{
    'USE_TEST_ADS': 'false',
    'SUPABASE_URL': '',
    'SUPABASE_ANON_KEY': '',
    'PREMIUM_AD_UNIT_ID': '',
    'QUICK_AD_UNIT_ID': '',
    'PREMIUM_AD_UNIT_ID_IOS': '',
    'QUICK_AD_UNIT_ID_IOS': '',
    'TEST_AD_UNIT_ID_ANDROID': '',
    'TEST_INTERSTITIAL_ID_ANDROID': '',
    'TEST_REWARDED_INTERSTITIAL_ID_ANDROID': '',
    'TEST_AD_UNIT_ID_IOS': '',
    'TEST_INTERSTITIAL_ID_IOS': '',
    'TEST_REWARDED_INTERSTITIAL_ID_IOS': '',
    'TAPJOY_SDK_KEY_IOS': '',
    'TAPJOY_SDK_KEY_ANDROID': '',
    'TAPJOY_REPORTING_API_KEY': '',
    'TAPJOY_SECRET': '',
    'TAPJOY_PLACEMENT_NAME': 'Offerwall',
    'PUBSCALE_APP_ID': '',
    'PUBSCALE_APP_ID_IOS': '',
    'PUBSCALE_SECRET': '',
    'PUBSCALE_SECRET_IOS': '',
    'PUBSCALE_SANDBOX': 'true',
    'GOOGLE_WEB_CLIENT_ID': '',
    'GOOGLE_IOS_CLIENT_ID': '',
    'UPSTASH_REDIS_REST_URL': '',
    'UPSTASH_REDIS_REST_TOKEN': '',
    'INTEGRATION_TEST': 'false',
  };

  final merged = {...defaults, ...secrets};

  for (final entry in merged.entries) {
    final escapedValue = entry.value.replaceAll(r'\', r'\\').replaceAll("'", r"\'");
    buf.writeln("  static const String ${entry.key} = '$escapedValue';");
  }

  // Convenience bool getters
  buf.writeln('');
  buf.writeln('  static bool get useTestAds => USE_TEST_ADS == \'true\';');
  buf.writeln('  static bool get isIntegrationTest => INTEGRATION_TEST == \'true\';');
  buf.writeln('  static bool get pubscaleSandbox => PUBSCALE_SANDBOX == \'true\';');
  buf.writeln('}');

  outputFile.writeAsStringSync(buf.toString());
}

/// Finds the Flutter project root by walking up until pubspec.yaml is found
Directory _findProjectRoot() {
  var dir = Directory.current;
  while (!File('${dir.path}/pubspec.yaml').existsSync()) {
    final parent = dir.parent;
    if (parent.path == dir.path) {
      throw StateError('Could not find Flutter project root (no pubspec.yaml found)');
    }
    dir = parent;
  }
  return dir;
}
