/**
 * RBX Rewards Android Application Build Configuration
 * Copyright (c) 2024-2026 Abdelkrim Salaghe & Youssef. All rights reserved.
 * Founder & Lead Developer: Abdelkrim Salaghe
 * Co-Founder & Publishing Partner: Youssef
 */

import java.util.Properties

plugins {
    id("com.android.application")
    id("kotlin-android")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

// ── Pre-build: Generate app_secrets.dart from env.json ───────────────────────
// Runs automatically before every `flutter run` and `flutter build`.
// Uses dart bundled with the Flutter SDK to avoid PATH issues on Windows/CI.
val flutterProjectRoot: File = project.rootDir.parentFile

// Read Flutter SDK path from local.properties (auto-generated by Flutter)
val localProperties = Properties()
val localPropertiesFile: File = rootProject.file("local.properties")
if (localPropertiesFile.exists()) {
    localPropertiesFile.inputStream().use { stream -> localProperties.load(stream) }
}
val flutterSdkPath: String = localProperties.getProperty("flutter.sdk")
    ?: error("flutter.sdk not set in local.properties. Run 'flutter pub get' first.")

val isWindows: Boolean = System.getProperty("os.name").lowercase().contains("windows")
val dartExecutable: String = if (isWindows) {
    "$flutterSdkPath\\bin\\dart.bat"
} else {
    "$flutterSdkPath/bin/dart"
}

tasks.register<Exec>("generateSecrets") {
    description = "Generates lib/core/config/app_secrets.dart from env.json"
    group = "rbx"
    workingDir = flutterProjectRoot
    commandLine(dartExecutable, "run", "tool/generate_secrets.dart")
}

tasks.named("preBuild") {
    dependsOn("generateSecrets")
}

tasks.matching { it.name.startsWith("compileFlutterBuild") }.configureEach {
    dependsOn("generateSecrets")
}
// ─────────────────────────────────────────────────────────────────────────────

android {
    namespace = "com.example.rbx_rewards"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        isCoreLibraryDesugaringEnabled = true
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    defaultConfig {
        applicationId = "com.example.rbx_rewards"
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    buildTypes {
        release {
            signingConfig = signingConfigs.getByName("debug")
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }
}

flutter {
    source = "../.."
}

dependencies {
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.4")
    implementation("com.tapjoy:tapjoy-android-sdk:14.4.0")
    implementation("com.pubscale.sdkone:offerwall:1.0.11")
}
